# Generated by Django 2.1.3 on 2018-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='obrazki/')),
                ('podpis', models.CharField(max_length=245)),
            ],
        ),
    ]
