# Generated by Django 2.1.3 on 2018-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181111_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
